services:
    mp-models-devcontainer:
        network_mode: host
        image: mp-models-devcontainer
        container_name: mp-models-devcontainer
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
            ssh:
                - default
            args:
                - PYTHON_VERSION
                - PIP_VERSION
                - DEVCONTAINER_USER
        volumes:
            - ..:/workspace:cached
            - ../resources/:/resources
        # This keeps the devcontainer running.
        entrypoint: [ "tail", "-f", "/dev/null" ]
